databases:
  - name: planka-db
    plan: free
    postgresMajorVersion: 14

services:
  - type: web
    name: planka
    plan: free
    env: docker
    repo: https://github.com/ItIsI-Orient/planka-render
    envVars:
      # BASE_URL has been removed
      - key: DATABASE_URL
        fromDatabase:
          name: planka-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: TRUST_PROXY
        value: true
      - key: DEFAULT_ADMIN_EMAIL
        value: 'filip.kruzik@webkomplet.cz'
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false
