databases:
  - name: planka-db
    plan: free
    postgresMajorVersion: 14

services:
  - type: web
    name: planka
    plan: free
    env: docker
    repo: https://github.com/ItIsI-Orient/planka-render
    envVars:
      - key: BASE_URL
        value: $RENDER_EXTERNAL_URL
      - key: DATABASE_URL
        fromDatabase:
          name: planka-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: TRUST_PROXY
        value: true
