databases:
  - name: planka-db
    plan: free
    postgresMajorVersion: 14

services:
  - type: web
    name: planka
    plan: free
    env: docker
    repo: https://github.com/ItIsI-Orient/planka-render
    envVars:
      # Use the built-in Render environment variable for the URL
      - key: BASE_URL
        value: $RENDER_EXTERNAL_URL
      - key: DATABASE_URL
        fromDatabase:
          name: planka-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true # Render will automatically generate a secure secret key
